### ISSUE TITLE
05315000-b03-t01/p1.2.jpg Scherffgen OCR? (Statdhalterhof)

### ISSUE THREAD

**Issue by a2800276** [codeforcologne/kulturpfade#75]
"... Scherffgen ... Heute erinnert noch eine Straße"

Zumindest im Internet heißt die Familie Scherfgin und die Straße auch. Bin nicht sicher ob das ein Fall von "das internet weiß nicht alles" oder ein OCR Fehler ist.

Sind die Scans irgendwo zu gegenlesen?

**Comment by weberius** [comment]
Im Zweifel ist es ein OCR-Fehler.
Ich habe Dir das Google Drive Verzeichnis freigegeben.

**Comment by a2800276** [comment]
Das Original für Müngersdorf is leider nicht dabei :rofl:

**Comment by weberius** [comment]
Ja klar! Sorry.
Müngersdorf hat einen neuen Pfad gestaltet, der weicht erheblich vom Original ab. Habe ich übernommen. Ich muss mir das mal ansehen.
Danke für den Hinweis.

**Comment by weberius** [comment]
Hab nochmal nachgesehen. 
Das notwendige Dokument befindet sich jetzt im Google Drive.
Es ist tatsächlich der Statthalterhof und auf dem Schild steht "Scherffgen".
Ich habe mir ein Ticket gemacht und werde es bearbeiten.
Danke für die Recherche.
